name: JD_DailyBonus.js Package

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    # 这里的时间为 UTC 时间，在 0 点运行，则在北京时间早上 8 点运行

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: JD_DailyBonus.js
